[tool.poetry]
authors = ["Lim"]
description = ""
name = "wiggle-example"
version = "0.1.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pycairo = { version = "^1.26" }
scipy = { version = "^1.14" }
huygens = { git = "https://github.com/punkdit/huygens.git", branch = "master" }
